-- Clip Inbox Supabase migration SQL
-- Daily Coreと同じSupabaseプロジェクトのSQL Editorで実行する。

create table if not exists public.clip_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,

  url text not null,
  duplicate_key text not null,
  title text,
  thumbnail_url text,
  reason text default '',
  tags text default '',

  status text default '未整理',
  is_private boolean default false,
  is_favorite boolean default false,

  watch_status text default 'あとで見る',
  watch_count integer default 0,
  last_watched_at timestamptz,
  watch_due_type text default 'none',
  watch_due_at timestamptz,

  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  deleted_at timestamptz,

  unique (user_id, duplicate_key)
);

create index if not exists clip_items_user_created_idx
on public.clip_items (user_id, created_at desc);

create index if not exists clip_items_user_deleted_idx
on public.clip_items (user_id, deleted_at);

alter table public.clip_items enable row level security;

drop policy if exists "clip_items_select_own" on public.clip_items;
create policy "clip_items_select_own"
on public.clip_items for select
using (auth.uid() = user_id);

drop policy if exists "clip_items_insert_own" on public.clip_items;
create policy "clip_items_insert_own"
on public.clip_items for insert
with check (auth.uid() = user_id);

drop policy if exists "clip_items_update_own" on public.clip_items;
create policy "clip_items_update_own"
on public.clip_items for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "clip_items_delete_own" on public.clip_items;
create policy "clip_items_delete_own"
on public.clip_items for delete
using (auth.uid() = user_id);
